version: '3.8'

services:
  api:
    build: 
      context: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=${HOSTPOSTGRES}
      - DB_PORT=${PORTPOSTGRES}
      - DB_USER=${USERPOSTGRES}
      - DB_PASSWORD=${PASSWORDPOSTGRES}
      - DB_NAME=${DBNAME}
    depends_on:
      - database

  database:
    image: postgres:13
    environment:
      POSTGRES_USER: ${USERPOSTGRES}
      POSTGRES_PASSWORD: ${PASSWORDPOSTGRES}
      POSTGRES_DB: ${DBNAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
